language: c
compiler: clang

script:
    - cmake .
    - make

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libx11-dev libimlib2-dev libbsd-dev python3-sphinx

env:
  global:
   - secure: "Hf1xjFClKIhsv4o4HqAs8pAqKdauJ3TItMH1uqc0qaPRmh0bFhNs0pwwjhmMjnLrbRrRcnfjwEyuXz3wZysiegSedm/tE0NyMFQql+rjgicmTQj73BMzrIDadQ8jMNaeD44YVDlFknv0ren9/LmSFzYLuI8zjAtIyeKxN++IujE="

addons:
  coverity_scan:
    project:
      name: "kyrias/yawa"
      description: "Build submitted via Travis CI"
    notification_email: johannes@kyriasis.com
    build_command_prepend: cov-configure --template --comptype clangcc --compiler clang; cmake .
    build_command: make
    branch_pattern: coverity_scan
