language: c
compiler: clang
script: ./scripts/travis_run.sh
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libx11-dev libimlib2-dev libbsd-dev

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Hf1xjFClKIhsv4o4HqAs8pAqKdauJ3TItMH1uqc0qaPRmh0bFhNs0pwwjhmMjnLrbRrRcnfjwEyuXz3wZysiegSedm/tE0NyMFQql+rjgicmTQj73BMzrIDadQ8jMNaeD44YVDlFknv0ren9/LmSFzYLuI8zjAtIyeKxN++IujE="

addons:
  coverity_scan:
    project:
      name: "kyrias/yawa"
      description: "Build submitted via Travis CI"
    notification_email: johannes@kyriasis.com
    build_command_prepend: "cmake -g 'Unix Makefiles'; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
